name: VNC-macOS

on:
  workflow_dispatch:

jobs:
  vnc-macos:
    runs-on: macos-latest
    timeout-minutes: 360

    steps:
      - name: Set up VNC user
        run: |
          PASSWORD=$(openssl rand -base64 12)
          echo "VNC_PASSWORD=$PASSWORD" >> $GITHUB_ENV

          # Create user
          sudo sysadminctl -addUser vncuser -password "$PASSWORD"
          sudo dseditgroup -o edit -a vncuser -t user admin

          echo "VNC_CREDS=User: vncuser | Password: $PASSWORD" >> $GITHUB_ENV

      - name: Enable VNC (Screen Sharing)
        run: |
          # Enable Remote Management and VNC
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -activate -configure -access -on \
            -users vncuser -privs -all \
            -restart -agent -menu

          # Set VNC password
          echo -n "$VNC_PASSWORD" | perl -we 'print pack("H*", "01000000000000000000000000000000"); while (read(STDIN,$c,1)) { print $c }' \
            | sudo tee /Library/Preferences/com.apple.VNCSettings.txt >/dev/null

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-vnc-${GITHUB_RUN_ID} --ssh

          TS_IP=$(tailscale ip -4 | head -n1)
          echo "TAILSCALE_IP=$TS_IP" >> $GITHUB_ENV

      - name: Verify VNC Port
        run: |
          echo "Tailscale IP: $TAILSCALE_IP"
          nc -zv $TAILSCALE_IP 5900 || (echo "VNC port not reachable" && exit 1)
          echo "VNC is accessible!"

      - name: Maintain VNC Session
        run: |
          echo -e "\n=== VNC ACCESS ==="
          echo "Address: $TAILSCALE_IP:5900"
          echo "Username: vncuser"
          echo "Password: $VNC_PASSWORD"
          echo "==================\n"

          while true; do
            echo "[$(date)] VNC Active - cancel workflow to terminate"
            sleep 300
          done
